services:
  eventscraper:
    container_name: cteventsc
    build:
      context: ../../
      dockerfile: ./CTEventEngine/docker/Dockerfile
    develop:
      watch:
        - action: sync
          path: ct_event_engine
          target: /app/ct_event_engine
    security_opt:
      - no-new-privileges:true
    env_file: docker.env
    networks:
        - cteventengine

networks:
    cteventengine:
